"""Initial migration with green design

Revision ID: 809d562e54c6
Revises: 
Create Date: 2026-02-08 17:20:44.779541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '809d562e54c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('user')
    op.drop_table('chat_messages')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialist_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_constraint('exercises_created_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['specialist_id'], ['id'])
        batch_op.drop_column('created_by')
        batch_op.drop_column('equipment_needed')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))

    with op.batch_alter_table('posture_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('body_front_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('body_side_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('body_back_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('face_front_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('posture_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('face_symmetry_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('deviations', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('analysis_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ai_model_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_recommendations', sa.Text(), nullable=True))
        batch_op.drop_column('analysis_date')
        batch_op.drop_column('side_image')
        batch_op.drop_column('front_image')
        batch_op.drop_column('analysis_results')
        batch_op.drop_column('face_image')
        batch_op.drop_column('is_completed')
        batch_op.drop_column('back_image')
        batch_op.drop_column('overall_score')

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('frequency', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('specialist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_constraint('recommendations_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['patient_id'], ['id'])
        batch_op.drop_column('duration_days')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')
        batch_op.drop_column('is_completed')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('subscription_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.alter_column('subscription_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index('ix_users_email')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_users_email', ['email'], unique=True)
        batch_op.alter_column('subscription_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('last_login')
        batch_op.drop_column('date_created')
        batch_op.drop_column('subscription_end')
        batch_op.drop_column('phone')

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recommendations_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('specialist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('date_modified')
        batch_op.drop_column('date_created')
        batch_op.drop_column('video_url')
        batch_op.drop_column('duration')
        batch_op.drop_column('frequency')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('posture_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('back_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('face_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('analysis_results', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('front_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('side_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('analysis_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('ai_recommendations')
        batch_op.drop_column('ai_model_version')
        batch_op.drop_column('status')
        batch_op.drop_column('analysis_data')
        batch_op.drop_column('deviations')
        batch_op.drop_column('face_symmetry_score')
        batch_op.drop_column('posture_score')
        batch_op.drop_column('face_front_image')
        batch_op.drop_column('body_back_image')
        batch_op.drop_column('body_side_image')
        batch_op.drop_column('body_front_image')
        batch_op.drop_column('date_created')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('equipment_needed', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exercises_created_by_fkey', 'users', ['created_by'], ['id'])
        batch_op.alter_column('difficulty',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('date_created')
        batch_op.drop_column('specialist_id')

    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_messages_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_messages_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey'),
    sa.UniqueConstraint('user_id', name='subscriptions_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
